import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const p = await b.newPage({ viewport: { width: 390, height: 844 } })
await p.goto('http://localhost:4173/')
await p.waitForTimeout(700)
await p.getByText('Progreso', { exact: true }).first().click()
await p.waitForTimeout(600)
await p.locator('.item-tap').first().click()
await p.waitForTimeout(600)
await p.locator('.picker-list').first().evaluate((n) => (n.scrollTop = n.scrollHeight))
await p.waitForTimeout(400)
await p.screenshot({ path: '/tmp/shots/detalle-4-abajo.png' })
await b.close()
